import { db } from '@/db';
import { menuItems } from '@/db/schema';

async function main() {
    const sampleMenuItems = [
        {
            categoryId: 1,
            name: 'Humus',
            description: 'Nohut, tahin, zeytinyağı ve limon suyu ile hazırlanan klasik Orta Doğu mezesi',
            price: '₺65',
            imageUrl: null,
            popular: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 1,
            name: 'Acılı Ezme',
            description: 'Domates, biber, soğan, nar ekşisi ve baharatlarla hazırlanan geleneksel ezme',
            price: '₺70',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 1,
            name: 'Haydari',
            description: 'Süzme yoğurt, maydonoz, dereotu, sarımsak ve ceviz ile',
            price: '₺75',
            imageUrl: null,
            popular: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 1,
            name: 'Patlıcan Salatası',
            description: 'Közlenmiş patlıcan, yoğurt, sarımsak ve zeytinyağı',
            price: '₺80',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 1,
            name: 'Atom',
            description: 'Ceviz, sarımsak, biber ve baharatlarla hazırlanan acılı meze',
            price: '₺75',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 1,
            name: 'Babaganuş',
            description: 'Közlenmiş patlıcan, tahin ve zeytinyağı ile',
            price: '₺70',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 1,
            name: 'Cacık',
            description: 'Yoğurt, salatalık, sarımsak, nane ve zeytinyağı',
            price: '₺60',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 2,
            name: 'Sigara Böreği',
            description: 'İçi beyaz peynir ve maydanozlu çıtır yufka böreği (6 adet)',
            price: '₺85',
            imageUrl: null,
            popular: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 2,
            name: 'Çiğ Köfte',
            description: 'Bulgur, domates, biber salçası ve baharatlarla yoğrulmuş (8 adet)',
            price: '₺90',
            imageUrl: null,
            popular: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 2,
            name: 'Kalamar Tava',
            description: 'Çıtır kalamar halkası, tartar sos ile',
            price: '₺120',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 2,
            name: 'Hellim Kızartması',
            description: 'Kıbrıs hellim peyniri, naneli yoğurt ile',
            price: '₺95',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 2,
            name: 'Falafel',
            description: 'Nohut köftesi, tahin sos ile (6 adet)',
            price: '₺80',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 2,
            name: 'Humus Kavurma',
            description: 'Sıcak humus üzerine kavurma et',
            price: '₺110',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 3,
            name: 'İskender Kebap',
            description: 'Döner eti, yoğurt, tereyağı ve domates sosu ile',
            price: '₺145',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 3,
            name: 'Adana Kebap',
            description: 'Şiş kıyma, közlenmiş sebzeler ve pilav ile',
            price: '₺140',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 3,
            name: 'Kuzu Şiş',
            description: 'Marine edilmiş kuzu şiş, pilav ve közlenmiş sebzeler',
            price: '₺150',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 3,
            name: 'Karışık Izgara',
            description: 'Kuzu pirzola, tavuk şiş, adana, pilav ve meze ile',
            price: '₺180',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 4,
            name: 'Ayran',
            description: 'Geleneksel yoğurt içeceği',
            price: '₺20',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 4,
            name: 'Şalgam Suyu',
            description: 'Acılı veya acısız',
            price: '₺25',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            categoryId: 4,
            name: 'Türk Çayı',
            description: 'Geleneksel demleme çay',
            price: '₺15',
            imageUrl: null,
            popular: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
    ];

    await db.insert(menuItems).values(sampleMenuItems);
    
    console.log('✅ Menu items seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});